# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default='category', on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default='location', on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Location'),
        ),
    ]
