# Generated by Django 3.0.7 on 2020-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200626_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
